# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseDirButton.setGeometry(QtCore.QRect(40, 20, 111, 23))
        self.chooseDirButton.setObjectName("chooseDirButton")
        self.dirPathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.dirPathLine.setGeometry(QtCore.QRect(160, 20, 371, 20))
        self.dirPathLine.setObjectName("dirPathLine")
        self.svnUrlLine = QtWidgets.QLineEdit(self.centralwidget)
        self.svnUrlLine.setGeometry(QtCore.QRect(160, 50, 371, 20))
        self.svnUrlLine.setToolTip("")
        self.svnUrlLine.setObjectName("svnUrlLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 101, 20))
        self.label.setObjectName("label")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(610, 20, 131, 23))
        self.checkButton.setObjectName("checkButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 130, 761, 421))
        self.textEdit.setObjectName("textEdit")
        self.switchButton = QtWidgets.QPushButton(self.centralwidget)
        self.switchButton.setGeometry(QtCore.QRect(610, 50, 75, 23))
        self.switchButton.setObjectName("switchButton")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(30, 100, 751, 23))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "分支检查转化"))
        self.chooseDirButton.setText(_translate("MainWindow", "选择本地文件夹"))
        self.svnUrlLine.setPlaceholderText(_translate("MainWindow", "请输入需要转化的分支url"))
        self.label.setText(_translate("MainWindow", "需要转化的分支:"))
        self.checkButton.setText(_translate("MainWindow", "检查当前文件夹分支"))
        self.switchButton.setText(_translate("MainWindow", "切换"))
